version: "3.3"

volumes:
  pg_project:

services:

  react-prod:
    restart: always
    container_name: react-prod
    build:
      context: .
      dockerfile:
        Dockerfile
    ports:
      - "80:80"
  pg_db:
    container_name: pg_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Sven1998
      - POSTGRES_USER=localuser
      - POSTGRES_DB=tc_database
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - pg_project:/var/lib/postgresql/data
  server:
    restart: always
    container_name: server
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ../backend/backend/.env
    depends_on:
      - pg_db
      - react-prod

  nginx:
    container_name: server_nginx
    restart: always
    image: nginx
    expose:
      - 8000
    ports:
    - 8000:8000
    volumes:
    - ../backend/static:/usr/src/app/static
    - ../backend/media:/usr/src/app/media
    - ../backend/logs:/usr/src/app/logs
    depends_on:
      - server
      - pg_db
      - react-prod



